### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigen.github.io#50]
```[tasklist]
### Tasks
- [ ] https://github.com/ocsigen/ocsigen.github.io/issues/51
- [ ] https://github.com/ocsigen/html_of_wiki/issues/140
- [ ] https://github.com/ocsigen/ocsigen.github.io/issues/53
- [ ] https://github.com/ocsigen/ocsigen.github.io/issues/54
- [ ] https://github.com/ocsigen/wikidoc/issues/18
```
